name: studytrace
description: "StudyTrace - 大学生课程任务管理与 AI 学习周报生成 App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.20
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  animations: ^2.0.11
  shared_preferences: ^2.3.3
  table_calendar: ^3.1.2
  fl_chart: ^0.69.2
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.15.1
  speech_to_text: ^7.3.0
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  path_provider: ^2.1.5
  flutter_markdown: ^0.7.3
  lordicon: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "logo/app图标.png"
  adaptive_icon_background: "#7040F2"
  adaptive_icon_foreground: "logo/app图标.png"
  web:
    generate: true
    image_path: "logo/app图标.png"
    background_color: "#7040F2"
    theme_color: "#7040F2"
  windows:
    generate: true
    image_path: "logo/app图标.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "logo/app图标.png"

flutter:
  uses-material-design: true
  assets:
    - assets/login/
    - assets/RiveAssets/
    - assets/Backgrounds/
    - assets/avatars/
    - assets/icons/
    - assets/icons/lordicon/
    - assets/Fonts/
    - logo/
