export type VivoCapabilityStatus = 'live' | 'partial' | 'planned' | 'manual';

export type VivoCapabilityAuthMode =
  | 'bearer'
  | 'gateway-signature'
  | 'local-sdk'
  | 'none';

export type VivoCapabilityProtocol =
  | 'http-json'
  | 'http-form'
  | 'http-multipart'
  | 'http-task'
  | 'websocket'
  | 'sdk'
  | 'prompt';

export type VivoAigcCapability = {
  slug: string;
  docId: number;
  name: string;
  category: string;
  status: VivoCapabilityStatus;
  protocol: VivoCapabilityProtocol;
  authMode: VivoCapabilityAuthMode;
  officialEndpoints: readonly string[];
  methods: readonly string[];
  models?: readonly string[];
  engineIds?: readonly string[];
  studyTraceEndpoints: readonly string[];
  envKeys: readonly string[];
  notes?: string;
};

export const vivoAigcCapabilities = [
  {
    slug: 'large-model',
    docId: 1745,
    name: '大模型',
    category: '文本生成',
    status: 'live',
    protocol: 'http-json',
    authMode: 'bearer',
    officialEndpoints: ['https://api-ai.vivo.com.cn/v1/chat/completions'],
    methods: ['POST'],
    models: [
      'Volc-DeepSeek-V3.2',
      'Doubao-Seed-2.0-mini',
      'Doubao-Seed-2.0-lite',
      'Doubao-Seed-2.0-pro',
      'qwen3.5-plus',
    ],
    studyTraceEndpoints: [
      '/ai/chat',
      '/ai/chat/stream',
      '/ai/study-log',
      '/ai/task-plan',
      '/ai/weekly-plan',
      '/ai/learning-loop',
      '/ai/weekly-analysis',
      '/ai/risk-warnings',
      '/ai/flash-cards',
      '/ai/rewrite',
      '/ai/grade-flashcard',
    ],
    envKeys: ['BLUEHEART_API_KEY', 'BLUEHEART_BASE_URL', 'BLUEHEART_MODEL'],
    notes: 'OpenAI-compatible chat completions. StudyTrace uses it for both general chat and study-specific generation.',
  },
  {
    slug: 'function-calling',
    docId: 1805,
    name: 'Function calling',
    category: '文本生成',
    status: 'live',
    protocol: 'prompt',
    authMode: 'none',
    officialEndpoints: [],
    methods: [],
    studyTraceEndpoints: ['/ai/chat'],
    envKeys: [],
    notes: 'Implemented as StudyTrace JSON actions and local tool registry prompts.',
  },
  {
    slug: 'image-generation',
    docId: 1732,
    name: '图片生成',
    category: '图片生成',
    status: 'live',
    protocol: 'http-json',
    authMode: 'bearer',
    officialEndpoints: ['https://api-ai.vivo.com.cn/api/v1/image_generation'],
    methods: ['POST'],
    models: ['Doubao-Seedream-4.5'],
    studyTraceEndpoints: ['/ai/images/tasks', '/ai/images/tasks/status'],
    envKeys: [
      'VIVO_IMAGE_GENERATION_PATH',
      'VIVO_IMAGE_SUBMIT_PATH',
      'VIVO_IMAGE_QUERY_PATH',
      'VIVO_IMAGE_BUSINESS_CODE',
      'VIVO_IMAGE_STYLE_DEFAULT',
    ],
    notes: 'Official document now describes synchronous image_generation. Existing StudyTrace code uses task submit/query paths for cover workflows.',
  },
  {
    slug: 'video-generation',
    docId: 2201,
    name: '视频生成',
    category: '视频生成',
    status: 'live',
    protocol: 'http-task',
    authMode: 'bearer',
    officialEndpoints: [
      'https://api-ai.vivo.com.cn/api/v1/submit_task',
      'https://api-ai.vivo.com.cn/api/v1/query_task',
    ],
    methods: ['POST', 'GET'],
    models: ['Doubao-Seedance-1.0-pro'],
    studyTraceEndpoints: ['/ai/videos/tasks', '/ai/videos/tasks/status'],
    envKeys: [
      'VIVO_VIDEO_SUBMIT_PATH',
      'VIVO_VIDEO_QUERY_PATH',
      'VIVO_VIDEO_MODEL',
      'VIVO_VIDEO_RATIO_DEFAULT',
      'VIVO_VIDEO_RESOLUTION_DEFAULT',
      'VIVO_VIDEO_DURATION_DEFAULT',
    ],
    notes: 'Task submit/query is exposed through StudyTrace backend. Contest document mentions daily 5 tasks and total 50 generated videos in the initial period.',
  },
  {
    slug: 'general-ocr',
    docId: 1737,
    name: '通用OCR',
    category: '视觉技术',
    status: 'live',
    protocol: 'http-form',
    authMode: 'bearer',
    officialEndpoints: ['http://api-ai.vivo.com.cn/ocr/general_recognition'],
    methods: ['POST'],
    studyTraceEndpoints: ['/ai/ocr'],
    envKeys: ['BLUEHEART_APP_ID', 'BLUEHEART_API_KEY'],
    notes: 'Frontend OcrService falls back to local MLKit when backend OCR fails.',
  },
  {
    slug: 'text-translation',
    docId: 1733,
    name: '文本翻译',
    category: '自然语言处理',
    status: 'live',
    protocol: 'http-json',
    authMode: 'bearer',
    officialEndpoints: ['https://api-ai.vivo.com.cn/translation/query/self'],
    methods: ['POST'],
    studyTraceEndpoints: ['/ai/translate'],
    envKeys: ['VIVO_TRANSLATE_PATH', 'VIVO_TRANSLATE_APP_NAME'],
    notes: 'Official text length limit is 1200 UTF-8 characters.',
  },
  {
    slug: 'text-embedding',
    docId: 1734,
    name: '文本向量',
    category: '自然语言处理',
    status: 'live',
    protocol: 'http-json',
    authMode: 'bearer',
    officialEndpoints: ['https://api-ai.vivo.com.cn/embedding-model-api/predict/batch'],
    methods: ['POST'],
    models: ['m3e-base', 'bge-base-zh-v1.5'],
    studyTraceEndpoints: ['/ai/embeddings', '/ai/memory/index', '/ai/memory/search'],
    envKeys: ['VIVO_EMBEDDING_ENDPOINT', 'VIVO_VECTOR_MODEL'],
    notes: 'Official FAQ recommends text length under 500 Chinese characters.',
  },
  {
    slug: 'text-rerank',
    docId: 2060,
    name: '文本相似度',
    category: '自然语言处理',
    status: 'live',
    protocol: 'http-json',
    authMode: 'bearer',
    officialEndpoints: ['https://api-ai.vivo.com.cn/rerank'],
    methods: ['POST'],
    models: ['bge-reranker-large'],
    studyTraceEndpoints: ['/ai/rerank'],
    envKeys: ['BLUEHEART_API_KEY'],
    notes: 'Used by semantic search with local fallback.',
  },
  {
    slug: 'query-rewrite',
    docId: 2061,
    name: '查询改写',
    category: '自然语言处理',
    status: 'live',
    protocol: 'http-json',
    authMode: 'bearer',
    officialEndpoints: ['https://api-ai.vivo.com.cn/query_rewrite_base'],
    methods: ['POST'],
    studyTraceEndpoints: ['/ai/query-rewrite'],
    envKeys: ['BLUEHEART_API_KEY'],
    notes: 'Used before local/rerank memory search.',
  },
  {
    slug: 'short-asr',
    docId: 1738,
    name: '实时短语音识别',
    category: 'ASR',
    status: 'partial',
    protocol: 'websocket',
    authMode: 'bearer',
    officialEndpoints: ['ws://api-ai.vivo.com.cn/asr/v2'],
    methods: ['WEBSOCKET'],
    engineIds: ['shortasrinput'],
    studyTraceEndpoints: ['/ai/speech/transcribe'],
    envKeys: ['VIVO_ASR_ENDPOINT', 'VIVO_ASR_ENGINE_ID', 'VIVO_ASR_WS_URL'],
    notes: 'Existing endpoint is an optional backend adapter, not the full official websocket protocol.',
  },
  {
    slug: 'long-asr-dictation',
    docId: 1740,
    name: '长语音听写',
    category: 'ASR',
    status: 'planned',
    protocol: 'websocket',
    authMode: 'bearer',
    officialEndpoints: ['ws://asr-test-v2.vivo.com.cn/asr/v2'],
    methods: ['WEBSOCKET'],
    studyTraceEndpoints: [],
    envKeys: ['VIVO_LONG_ASR_WS_URL'],
    notes: 'Long utterance websocket dictation requires a dedicated streaming design.',
  },
  {
    slug: 'long-audio-transcription',
    docId: 1739,
    name: '长语音转写',
    category: 'ASR',
    status: 'planned',
    protocol: 'http-task',
    authMode: 'bearer',
    officialEndpoints: [
      '/lasr/create',
      '/lasr/upload',
      '/lasr/run',
      '/lasr/progress',
      '/lasr/result',
    ],
    methods: ['POST', 'GET'],
    studyTraceEndpoints: [],
    envKeys: ['VIVO_LASR_BASE_URL'],
    notes: 'Official flow supports files up to 5 hours and under 500 MB; needs multipart/chunk upload handling.',
  },
  {
    slug: 'dialect-asr',
    docId: 2065,
    name: '方言自由说',
    category: 'ASR',
    status: 'planned',
    protocol: 'websocket',
    authMode: 'bearer',
    officialEndpoints: ['ws://api-ai.vivo.com.cn/asr/v2'],
    methods: ['WEBSOCKET'],
    engineIds: ['shortasrinput'],
    studyTraceEndpoints: [],
    envKeys: ['VIVO_DIALECT_ASR_WS_URL'],
    notes: 'Same base websocket protocol as realtime ASR with dialect language options.',
  },
  {
    slug: 'simultaneous-interpretation',
    docId: 2068,
    name: '同声传译',
    category: 'ASR',
    status: 'planned',
    protocol: 'websocket',
    authMode: 'bearer',
    officialEndpoints: ['ws://api-ai.vivo.com.cn/asr/v2'],
    methods: ['WEBSOCKET'],
    engineIds: ['longasrsubtitle'],
    studyTraceEndpoints: [],
    envKeys: ['VIVO_INTERPRETATION_WS_URL'],
    notes: 'Combines ASR, translation, and optional TTS fields.',
  },
  {
    slug: 'audio-generation',
    docId: 1735,
    name: '音频生成',
    category: 'TTS',
    status: 'planned',
    protocol: 'websocket',
    authMode: 'gateway-signature',
    officialEndpoints: ['wss://api-ai.vivo.com.cn/tts'],
    methods: ['WEBSOCKET'],
    engineIds: [
      'short_audio_synthesis_jovi',
      'long_audio_synthesis_screen',
      'tts_humanoid_lam',
    ],
    studyTraceEndpoints: [],
    envKeys: ['VIVO_TTS_WS_URL', 'VIVO_TTS_ENGINE_ID'],
    notes: '24 kHz, 16-bit, mono PCM. Current Flutter app mainly uses device TTS.',
  },
  {
    slug: 'voice-cloning',
    docId: 2062,
    name: '声音复刻',
    category: 'TTS',
    status: 'planned',
    protocol: 'http-multipart',
    authMode: 'gateway-signature',
    officialEndpoints: [
      '/replica/create_vcn_task',
      '/replica/get_vcn_task',
      '/replica/get_vcn_task_list',
      '/replica/del_task',
    ],
    methods: ['POST', 'GET'],
    studyTraceEndpoints: [],
    envKeys: ['VIVO_VOICE_CLONE_BASE_URL'],
    notes: 'Requires wav upload and task polling.',
  },
  {
    slug: 'poi-search',
    docId: 1736,
    name: '地理编码(POI搜索)',
    category: 'LBS',
    status: 'live',
    protocol: 'http-json',
    authMode: 'bearer',
    officialEndpoints: ['https://api-ai.vivo.com.cn/search/geo'],
    methods: ['GET'],
    studyTraceEndpoints: ['/ai/poi-search', '/ai/reverse-geocode'],
    envKeys: ['VIVO_POI_SEARCH_ENDPOINT', 'VIVO_REVERSE_GEOCODE_ENDPOINT', 'VIVO_POI_TOKEN'],
    notes: 'Official document covers POI search. Reverse geocode is kept as a StudyTrace business adapter.',
  },
  {
    slug: 'on-device-3b',
    docId: 1802,
    name: '端侧3B大模型',
    category: '端侧文本生成',
    status: 'manual',
    protocol: 'sdk',
    authMode: 'local-sdk',
    officialEndpoints: ['Android AAR/native SDK'],
    methods: ['SDK'],
    models: ['BlueLM'],
    studyTraceEndpoints: [],
    envKeys: [],
    notes: 'Requires Android native integration, arm64, and local model files such as /sdcard/1225.',
  },
  {
    slug: 'on-device-moderation',
    docId: 1804,
    name: '端侧文本审核',
    category: '端侧文本生成',
    status: 'manual',
    protocol: 'sdk',
    authMode: 'local-sdk',
    officialEndpoints: ['Android AAR SDK'],
    methods: ['SDK'],
    studyTraceEndpoints: [],
    envKeys: [],
    notes: 'Requires local Android moderation SDK integration.',
  },
  {
    slug: 'on-device-files',
    docId: 1803,
    name: '端侧能力相关文件',
    category: '端侧文本生成',
    status: 'manual',
    protocol: 'sdk',
    authMode: 'none',
    officialEndpoints: ['Official downloadable SDK/demo archives'],
    methods: ['DOWNLOAD'],
    studyTraceEndpoints: [],
    envKeys: [],
    notes: 'Records the official package list; files must be downloaded and reviewed manually.',
  },
] as const satisfies readonly VivoAigcCapability[];

export const liveVivoAigcCapabilities = vivoAigcCapabilities.filter(
  (capability) => capability.status === 'live',
);

export function findVivoAigcCapability(slug: string) {
  return vivoAigcCapabilities.find((capability) => capability.slug === slug);
}

export function vivoCapabilityLabel(slug: string, fallback: string) {
  return findVivoAigcCapability(slug)?.name ?? fallback;
}
